PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL UNIQUE,
    PasswordSalt TEXT NOT NULL,
    PasswordHash TEXT NOT NULL,
    FullName TEXT NOT NULL,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Balances (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    CurrencyCode TEXT NOT NULL,
    Amount REAL NOT NULL DEFAULT 0,
    UpdatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (UserId, CurrencyCode),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Transactions (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    Type TEXT NOT NULL,
    SourceCurrency TEXT NOT NULL,
    TargetCurrency TEXT NOT NULL,
    SourceAmount REAL NOT NULL,
    TargetAmount REAL NOT NULL,
    Rate REAL NOT NULL,
    Description TEXT NOT NULL,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_Balances_UserId ON Balances(UserId);
CREATE INDEX IF NOT EXISTS IX_Transactions_UserId_CreatedAt ON Transactions(UserId, CreatedAt DESC);
